### ISSUE TITLE
Save image 32 bit

### ISSUE THREAD

**Issue by Abocg** [kijai/ComfyUI-Geowizard#2]
Many thanks for your work but is there anyway I can save the generated map as 32 bit ? Am only getting.png 8 bit

**Comment by kijai** [comment]
In my Marigold -node pack I have node to save into EXR format: https://github.com/kijai/ComfyUI-Marigold

**Comment by LukeG89** [comment]
@Abocg You can also install this custom node: https://github.com/spacepxl/ComfyUI-HQ-Image-Save

**Comment by Abocg** [comment]
> In my Marigold -node pack I have node to save into EXR format: https://github.com/kijai/ComfyUI-Marigold

Thank you

**Comment by Abocg** [comment]
.
